require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/group_payments', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # GroupPayment. As you add validations to GroupPayment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      GroupPayment.create! valid_attributes
      get group_payments_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      group_payment = GroupPayment.create! valid_attributes
      get group_payment_url(group_payment)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_group_payment_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      group_payment = GroupPayment.create! valid_attributes
      get edit_group_payment_url(group_payment)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new GroupPayment' do
        expect do
          post group_payments_url, params: { group_payment: valid_attributes }
        end.to change(GroupPayment, :count).by(1)
      end

      it 'redirects to the created group_payment' do
        post group_payments_url, params: { group_payment: valid_attributes }
        expect(response).to redirect_to(group_payment_url(GroupPayment.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new GroupPayment' do
        expect do
          post group_payments_url, params: { group_payment: invalid_attributes }
        end.to change(GroupPayment, :count).by(0)
      end


      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post group_payments_url, params: { group_payment: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested group_payment' do
        group_payment = GroupPayment.create! valid_attributes
        patch group_payment_url(group_payment), params: { group_payment: new_attributes }
        group_payment.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the group_payment' do
        group_payment = GroupPayment.create! valid_attributes
        patch group_payment_url(group_payment), params: { group_payment: new_attributes }
        group_payment.reload
        expect(response).to redirect_to(group_payment_url(group_payment))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        group_payment = GroupPayment.create! valid_attributes
        patch group_payment_url(group_payment), params: { group_payment: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested group_payment' do
      group_payment = GroupPayment.create! valid_attributes
      expect do
        delete group_payment_url(group_payment)
      end.to change(GroupPayment, :count).by(-1)
    end

    it 'redirects to the group_payments list' do
      group_payment = GroupPayment.create! valid_attributes
      delete group_payment_url(group_payment)
      expect(response).to redirect_to(group_payments_url)
    end
  end
end
